#!/bin/sh
# run stats.py in the appropriate virtualenv.
#
# invoke periodically from crontab and direct the output to
# /var/www/tilde.town/tilde.json
exec /usr/local/virtualenvs/tildetown/bin/python /usr/local/tildetown-scripts/tildetown/stats.py
